version: "{build}"
image: "Windows Server 2019 on Azure for batect"
skip_tags: true
max_jobs: 20

environment:
  GRADLE_OPTS: "-Dorg.gradle.internal.launcher.welcomeMessageEnabled=false -Dorg.gradle.daemon=false"

install:
  - ver
  - java -version
  - python --version
  - bash --version

build_script:
  - ./gradlew --parallel app:check wrapper:windows:check jacocoTestReport
  - ps: |
      $env:Path = "C:\Program Files\Git\usr\bin;" + $env:Path
      bash -c 'export CI=True && export APPVEYOR=True && curl -s --show-error --fail --retry-connrefused --retry 10 https://codecov.io/bash | bash -s -- -F windows'
  - ps: ./appveyor/Enable-LinuxContainers.ps1
  - docker version
  - ./gradlew integrationTest
  - ./gradlew journeyTest
  - ps: ./appveyor/Enable-WindowsContainers.ps1
  - docker version

after_test:
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\modules-2\modules-2.lock
  - ps: Remove-Item -ErrorAction SilentlyContinue -Recurse ${env:USERPROFILE}\.gradle\caches\*\plugin-resolution\
  - ps: Remove-Item -ErrorAction SilentlyContinue -Recurse ${env:USERPROFILE}\.gradle\caches\*\scripts\
  - ps: Remove-Item -ErrorAction SilentlyContinue -Recurse ${env:USERPROFILE}\.gradle\caches\*\scripts-remapped\
  - ps: Remove-Item -ErrorAction SilentlyContinue -Recurse ${env:USERPROFILE}\.gradle\caches\*\fileHashes\
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\*\fileContent\*.lock
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\*\javaCompile\*.lock
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\*\executionHistory\*.lock
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\*\generated-gradle-jars\*.lock
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\jars-3\*.lock
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\journal-1\file-access.bin
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\journal-1\*.lock

cache:
  - '%USERPROFILE%\.gradle\caches'
  - '%USERPROFILE%\.gradle\wrapper'
