version: "{build}"
image: "Windows Server 2019"

environment:
  GRADLE_OPTS: "-Dorg.gradle.internal.launcher.welcomeMessageEnabled=false -Dorg.gradle.daemon=false"

install:
  - set PATH=C:\Python37;%PATH%
  - docker-switch-linux
  - docker version

build_script:
  - ./gradlew --parallel build check jacocoTestReport assembleRelease
  - ps: |
      $env:PATH = 'C:\msys64\usr\bin;' + $env:PATH
      Invoke-WebRequest -Uri 'https://codecov.io/bash' -OutFile build\codecov.sh
      bash build\codecov.sh -F windows
  - ./gradlew integrationTest
  - ./gradlew journeyTest

after_test:
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\modules-2\modules-2.lock
  - ps: Remove-Item -ErrorAction SilentlyContinue -Recurse ${env:USERPROFILE}\.gradle\caches\*\plugin-resolution\
  - ps: Remove-Item -ErrorAction SilentlyContinue -Recurse ${env:USERPROFILE}\.gradle\caches\*\scripts\
  - ps: Remove-Item -ErrorAction SilentlyContinue -Recurse ${env:USERPROFILE}\.gradle\caches\*\scripts-remapped\
  - ps: Remove-Item -ErrorAction SilentlyContinue -Recurse ${env:USERPROFILE}\.gradle\caches\*\fileHashes\
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\*\fileContent\*.lock
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\*\javaCompile\*.lock
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\*\executionHistory\*.lock
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\*\generated-gradle-jars\*.lock
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\jars-3\*.lock
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\journal-1\file-access.bin
  - ps: Remove-Item -ErrorAction SilentlyContinue          ${env:USERPROFILE}\.gradle\caches\journal-1\*.lock

cache:
  - '%USERPROFILE%\.gradle\caches'
  - '%USERPROFILE%\.gradle\wrapper'
