version: "{build}"
image: "Visual Studio 2017"

environment:
  GRADLE_OPTS: "-Dorg.gradle.internal.launcher.welcomeMessageEnabled=false -Dorg.gradle.daemon=false"

install:
  - set PATH=C:\Python37;%PATH%
#  - docker-switch-linux
  - docker version

build_script:
  - ./gradlew --parallel build check jacocoTestReport assembleRelease -x docs:buildDocs -x wrapper:unix:check && bash <(curl -s https://codecov.io/bash) -c -F windows

#test_script:
#  - ./gradlew integrationTest
#  - ./gradlew journeyTest

after_test:
  - ps: Remove-Item          ${env:USERPROFILE}\.gradle\caches\modules-2\modules-2.lock
  - ps: Remove-Item -Recurse ${env:USERPROFILE}\.gradle\caches\*\plugin-resolution\
  - ps: Remove-Item -Recurse ${env:USERPROFILE}\.gradle\caches\*\scripts\
  - ps: Remove-Item -Recurse ${env:USERPROFILE}\.gradle\caches\*\scripts-remapped\
  - ps: Remove-Item -Recurse ${env:USERPROFILE}\.gradle\caches\*\fileHashes\
  - ps: Remove-Item          ${env:USERPROFILE}\.gradle\caches\*\fileContent\*.lock
  - ps: Remove-Item          ${env:USERPROFILE}\.gradle\caches\*\javaCompile\*.lock
  - ps: Remove-Item          ${env:USERPROFILE}\.gradle\caches\*\executionHistory\*.lock
  - ps: Remove-Item          ${env:USERPROFILE}\.gradle\caches\*\generated-gradle-jars\*.lock
  - ps: Remove-Item          ${env:USERPROFILE}\.gradle\caches\jars-3\*.lock
  - ps: Remove-Item          ${env:USERPROFILE}\.gradle\caches\transforms-1\transforms-1.lock
  - ps: Remove-Item          ${env:USERPROFILE}\.gradle\caches\journal-1\file-access.bin
  - ps: Remove-Item          ${env:USERPROFILE}\.gradle\caches\journal-1\*.lock

cache:
  - '%USERPROFILE%\.gradle\caches'
  - '%USERPROFILE%\.gradle\wrapper'
