version: "{build}"
image: "Visual Studio 2017"

environment:
  GRADLE_OPTS: "-Dorg.gradle.internal.launcher.welcomeMessageEnabled=false"

install:
  - set PATH=C:\Python37;%PATH%
  - echo %PATH%
#  - docker-switch-linux
  - docker version

build_script:
  - ./gradlew --parallel build check jacocoTestReport assembleRelease -x docs:buildDocs -x wrapper:unix:check && bash <(curl -s https://codecov.io/bash) -c -F windows

#test_script:
#  - ./gradlew integrationTest
#  - ./gradlew journeyTest
