dist: xenial

language: java

jdk:
  - openjdk8

services:
  - docker

before_install:
  - sudo pip install gsutil
  - mkdir -p ~/.creds
  - openssl aes-256-cbc -K $encrypted_2210a3652f18_key -iv $encrypted_2210a3652f18_iv -in travis/travis-ci.json.enc -out ~/.creds/travis-ci.json -d
  - echo "[Credentials]" > ~/.boto
  - echo "gs_service_key_file = $HOME/.creds/travis-ci.json" >> ~/.boto

install: true

stages:
  - Build and test
  - Integration and journey test
  - Deploy

jobs:
  include:
    - stage: Build and test
      script:
        - ./gradlew build
        - ./gradlew check
        - ./gradlew jacocoTestReport
        - bash <(curl -s https://codecov.io/bash)
        - ./gradlew assembleRelease
      after_success:
        - gsutil rsync -r build/release gs://batect-artifacts/$TRAVIS_BUILD_ARTIFACTS/build/release
        - gsutil rsync -r docs/build/docs gs://batect-artifacts/$TRAVIS_BUILD_ARTIFACTS/docs/build/docs

    - stage: Integration and journey test
      script:
        - ./gradlew integrationTest
        - ./gradlew journeyTest

    - stage: Deploy
      script: skip
      if: tag IS present AND repo = "charleskorn/batect"
      before_deploy:
        - mkdir -p build/release docs/build/docs
        - gsutil rsync -r gs://batect-artifacts/$TRAVIS_BUILD_ARTIFACTS/build/release build/release
        - gsutil rsync -r gs://batect-artifacts/$TRAVIS_BUILD_ARTIFACTS/docs/build/docs docs/build/docs
        - ./gradlew validateRelease
      deploy:
        - provider: releases
          api_key:
            secure: wm/dkxB0NC7GWQzbeZBaLpDIEyCR7HhL/+GtWvQjfVDAGveH8mb7mCTiH8oBWB8mV4IRGYEBGq5daJcpVZide/EDDjDV2nLoQlhs0+YIV1vlsfYkOf29XBrV+8VBQlCsOSUqzuwzraOKM13/SMUtqGT4CAtGU0WGa9p3vI1UfevvKi0Ok3N0LLWdwEJ+nBNjDcWnHCfeMUSaFwQg4190iqxtBFphD1AKwAzaDAXHUHtMYjJpga6W0rIQMawEP65y71OWxnYnEYsUmV1RhhMsiVPVZzSsfXBTx81BWqRcTzyjEP18MChKj0Aaix+DJfrKBMYkLposdreicS9uqXTfb9CnMlr5z4EaJGdoIajmg2zLBooeY26EqN7Ub1+zj1HrRI0ORnO9++GHkRNB7dCmWw3BslURk2Z1hYDiHnaSvbG/nn5SmELtU6hipaNnTDHpiTuFli1lInl78feuUi20aTkOB2SRGg0aV/cezKBz/6aVPq2kB9hNzBeel0y/oKdOQlRAsvZbClcqf7Pv61I+zeUAnnHyqYH0pUuTHLzi3BN2gIsgqNUv0H+DxDo8pcAMw/YgAIf2bG88Rh1PODTdtaMJjXCkpcguypOJlrcLRnGQ5bk5/yQcVfT2hLcx9iWmbWKgK3J/fNxO9uxHqtt7u+s130qsgN8ELb4MoTsUAss=
          skip_cleanup: true
          file_glob: true
          file: build/release/*

        - provider: pages
          local-dir: docs/build/docs
          skip-cleanup: true
          github-token:
            secure: "vDvsBKorIMunrBkLJ4mjhikxhsL4Va0zqkBaJqkqodyT9nxfwU7OgzK9DyJ/5eqmqriajxYRX28Hc0n/k+YNIhz8kNIYRfKRlubjgZIXqGkclXOqE7lLLo2YlnXZ00pL4G/goOUNtEEtXQLFraD7fcLl9Kwg5A9lKH6fclA3scNlogTdCpS0quJtKVbEEkMDPq3wfBdDV7BFkm3IAjLI7I9HTyANRiVVoOSQtr8oQkVad7IAJn3yTLPPkQ7pC7gMPeL7qOO8cQNehrOyOujpqRh5/YihWVqOMXHjEreHnQDXSgKjz1NL+Xv66LnFRaMzkRNbZNYQ9hU7t2S7Ns9tEqUblK1msXZcNEd7b1EIJdEZgFmn6HytvHiLXE1dLrsczkazqnRIOvEz+sHb+d4ABo2ZqTl4rEapMbQiYjXjXvQAfmDIEjTh4mYepbXdVZcADISFlJ49KSqJdXdjaIM5pfO0IrQ1pFvuFA3XXxf/PQ2RGfq9I+Hv5qXb/U5HPLOa0P9w8LCpBJIbneqQ11JbNlZucgCyNgdsbmTUd6aZ463Lq/OrEXArwPt2x6xD2i8aNc/Lq9tl8cTSZYxGAQqTVp4KLxFQNeDdlSmW+rXINXH2FUiSxiWGdOjjVbMvGY8OfPe0NyWiswI9JQNmp4sxU2lqpgeMJS+lZw53f1uHxg8="
          target-branch: gh-pages
          keep-history: true

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.bin
  - rm -f  $HOME/.gradle/caches/*/fileHashes/fileHashes.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
