os: linux
dist: xenial

language: java

jdk:
  - openjdk8

git:
  depth: false

services:
  - docker

install: true

stages:
  - Build and unit test
  - Integration and journey test
  - Publish
  - Release

env:
  - GRADLE_OPTS=-Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  include:
    - stage: Build and unit test
      name: Linux
      script: ./gradlew --parallel build check jacocoTestReport assembleRelease integrationTestClasses journeyTestClasses && bash <(curl -s https://codecov.io/bash) -c -F linux
      workspaces:
        create:
          name: build_workspace
          paths:
            - .gradle/
            - build/
            - app/build/
            - app/src/main/kotlin/batect/VersionInfo.kt
            - buildSrc/build/
            - docs/build/
            - wrapper/build/
            - wrapper/testapp/build/
            - wrapper/unix/build/
            - wrapper/windows/build/

    - stage: Integration and journey test
      name: Integration test against latest Docker
      before_install: ./travis/install_docker.sh
      script: ./gradlew integrationTest
      workspaces:
        use:
          - build_workspace

    - stage: Integration and journey test
      name: Integration test against latest Docker (TLS over TCP)
      before_install:
        - ./travis/install_docker.sh
        - ./travis/configure_docker_tls.sh
      script: DOCKER_CERT_PATH=$HOME/.docker/certs DOCKER_TLS_VERIFY=1 DOCKER_HOST=tcp://localhost:2376 ./gradlew integrationTest
      workspaces:
        use:
          - build_workspace

    - stage: Integration and journey test
      name: Journey test against latest Docker
      before_install: ./travis/install_docker.sh
      script: ./gradlew journeyTest
      workspaces:
        use:
          - build_workspace

    - stage: Integration and journey test
      name: Integration test against Docker 18.03.1
      before_install: ./travis/install_docker.sh docker-ce=18.03.1~ce-0~ubuntu
      script: ./gradlew integrationTest
      workspaces:
        use:
          - build_workspace

    - stage: Integration and journey test
      name: Journey test against Docker 18.03.1
      before_install: ./travis/install_docker.sh docker-ce=18.03.1~ce-0~ubuntu
      script: ./gradlew journeyTest
      workspaces:
        use:
          - build_workspace

    - stage: Integration and journey test
      name: Wait for Windows build to complete
      if: (tag IS present OR branch = "master") AND repo = "batect/batect" AND type != pull_request
      script: ./travis/wait_for_appveyor.sh

    - stage: Release
      script: skip
      if: tag IS present AND repo = "batect/batect"
      workspaces:
        use:
        - build_workspace
      before_deploy: ./gradlew --parallel validateRelease
      deploy:
        - provider: bintray
          file: build/bintray/descriptor.json
          user: charleskorn
          key:
            secure: "gorxQBTZgKrgQ3Sc/veZX0b+Jh9b6xQxBOjcCPgp51rxXfea+115GrR+I7EG6soA6pnDdawy4TUTlzcKp4uwDlNmhTjWJuaCoVIbVPRfnLhL+wNYgwCeWLv9tocJWyn7RdtmNbfG3W9pSuWE+kaYplC/1I1golMxIIt/0M4OCMfy17oWJCd7LQRSjwPUMHrKgMFOrnQrfliK4fHYlLm35iz3pTvRfyv6AaTIhEstMubt1ljER5HMAtaVVA66rOhwGgUcyht2CqeZf/tonKhTFvsfDK0j2OBZqKetFB6aNorlBNVIr18EKokQmOZPEN1vyUHD0jkJ29w6wXBmeJJJ+nxiKBwiw73B+l9sutQ4DAKiSRfHnhCf5EMGsSKaOPFELCd8F3GoiG806sUtamqq9L7wg6EDd68nfo2gcxoDYYxSTxwBasvN4D8u/mAQkQeelSb5AbKjSSNZp0/umiM8dsVg8JP8oT3zKGBfpo5OUqi/PaDGmYnU32EmV1OYFMk/1BH8w5CXQybaTdY6LNHlEIM5RLiwhbbfUhBa/yNCR2BaZh3IWrq1CXO+3r3HzSE6E21VGcOT9MR0ZdnEpyBQLEGJfBElCkpaoAA6pW9uBEJJ5H4Hb84VoICF4AEN5gzo9KjbFOiz+4a7Wi7+TsqnfL4l/sAVUTa8lawXqX/NsDU="
          skip_cleanup: true
          on:
            repo: batect/batect
            all_branches: true

        - provider: releases
          api_key:
            secure: "j5HYmSbauZATCMRVmWe8cTRBw/q+uUq0a1kzHITMGhp8N0PIDtFliEsSNoyZjZnVAY7m/teWIshQm71wtq9t089gB4HuLwtMfXcVwCtP+WCy7XFij99cjaoB7AssZuAblzsUsnDMGeWPKCJSsqJZLA46FLHUoiQblWUe/WrEGbJCWzTc0Sc9A07zYsEIL69v/mmR9vKqUutE5C6DLAxdu33VJyyu/ZmsqwTSYztJOz/EfkmAIKM1jNsxH4F7UMpgJtWTfztykvCbIYre9UVXZPuibkHw+0V1n3EMc/TCn/GY2b1s5cVVwssIRceUieSV3cXeK3y/g+MlzNxQISmd/eveRNVAojABS8akTXZzbklT43nzLhMd8M9Gf2pjA4wn0m4E85jB9/rP3Ae8u1wb+g2ZSc6uXWu/Oi9wQgxL12x+RYiuHNGELfjJxPL3aHnPzKxkI6b388a40q68DbwvSQ3NOq1AfeDQJb/aMMO8Z4INpLN+wfLgVJ5iRLv4h9w8x9BR43tre8BzHNSWx44ESAl6h5nYj/wk/9jeE9vPwtz3zQDSRFC/ohvHz/YY1zP8GKH1R+JByYGFOjD9KA6/d6qkx/NALLSv9Zt+f+ReHIRa2/SBwSpQ7rg0h+LSDuHSJY2ZTcKqRmuekYmw1UBnV+IVvU2T3T74rjEOQ7VlqPg="
          skip_cleanup: true
          file_glob: true
          file: build/release/*
          on:
            # We skip this whole stage if we don't want to deploy, so just disable the checks here.
            condition: true
            all_branches: true

        - provider: pages
          local_dir: docs/build/docs
          skip_cleanup: true
          github_token:
            secure: "hhBskZA6ZFOhK+itsjTj5EEmOF/VT3IyfK484DM7IuVwrVHIewe/GdQRnBrO06eqsMNbcTMsRSxxinI1OBMwiP6wNMR/7CI1+CSbwltAD1LnPyY0/fONipzNyKtMgpR5SQ/RSZVs/mmO2QDuVVKgaTAW6v/jiMTxJiduW6aqn2kw0LzxamSVBQ3y5xhP86A9XarmEwk98d+M1FR+9WYlyW0d+XMvRZn7OjAR1Fr9nRPF3ca7LEokKAwcTc5IilUAoHFyqlZLDkMD6EvfUWUlx2GBduhzDwzRL/5OzlIcNUlURqhIEZ1xXpmLYLp8pp7Zch6yesee+6qxLXipEGnQErOBoak7ieSJc7jWeG6ecXQkTpI5rzW8fR8yIClbxfZvjV/kwuAtkG8lcoSIeko8hvy4md2YCgF14ASSgehu3TI8UuuKqkRl76HsVHdTa2ajrqc8cWqmPdEyJI5PUvZy8/7Z5VdN+mGo6+Npg+684IEshy+n5poH0BwOPKeFV4oxfuMAq7DxiltjlPyr5yNfWFVq5KtNzbg4Gsw1D4oL0paBRjE8N/2tlHFpzxHaCzV6gaH42o3pcVNhEgK02FQk6cH2rHTTg+3Se/pT9jYm+QeVfUx8WyUKcEkkcrtLOQTlQQI1FfFc49psOwAP4l8y1ZAMkXljIaLTI9O2P+Sgwp0="
          target_branch: gh-pages
          keep_history: true
          on:
            # We skip this whole stage if we don't want to deploy, so just disable the checks here.
            condition: true
            all_branches: true


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
  - rm -fr $HOME/.gradle/caches/*/scripts-remapped/
  - rm -fr $HOME/.gradle/caches/*/fileHashes/
  - rm -f  $HOME/.gradle/caches/*/fileContent/*.lock
  - rm -f  $HOME/.gradle/caches/*/javaCompile/*.lock
  - rm -f  $HOME/.gradle/caches/*/executionHistory/*.lock
  - rm -f  $HOME/.gradle/caches/*/generated-gradle-jars/*.lock
  - rm -f  $HOME/.gradle/caches/jars-3/*.lock
  - rm -f  $HOME/.gradle/caches/transforms-1/transforms-1.lock
  - rm -f  $HOME/.gradle/caches/journal-1/file-access.bin
  - rm -f  $HOME/.gradle/caches/journal-1/*.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
