os: linux
dist: xenial

language: java

jdk:
  - openjdk8

git:
  depth: false

services:
  - docker

install: true

stages:
  - Build and unit test
  - Integration and journey test
  - Publish
  - Release

env:
  - GRADLE_OPTS=-Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

jobs:
  include:
    - stage: Build and unit test
      name: Linux
      script: ./gradlew --parallel build check jacocoTestReport assembleRelease integrationTestClasses journeyTestClasses && bash <(curl -s https://codecov.io/bash) -c -F linux
      workspaces:
        create:
          name: build_workspace
          paths:
            - .gradle/
            - build/
            - app/build/
            - app/src/main/kotlin/batect/VersionInfo.kt
            - buildSrc/build/
            - docs/build/
            - wrapper/build/
            - wrapper/testapp/build/
            - wrapper/unix/build/
            - wrapper/windows/build/

    - stage: Integration and journey test
      name: Integration test against latest Docker
      before_install: ./travis/install_docker.sh
      script: ./gradlew integrationTest
      workspaces:
        use:
          - build_workspace

    - stage: Integration and journey test
      name: Integration test against latest Docker (TLS over TCP)
      before_install:
        - ./travis/install_docker.sh
        - ./travis/configure_docker_tls.sh
      script: DOCKER_CERT_PATH=$HOME/.docker/certs DOCKER_TLS_VERIFY=1 DOCKER_HOST=tcp://localhost:2376 ./gradlew integrationTest
      workspaces:
        use:
          - build_workspace

    - stage: Integration and journey test
      name: Journey test against latest Docker
      before_install: ./travis/install_docker.sh
      script: ./gradlew journeyTest
      workspaces:
        use:
          - build_workspace

    - stage: Integration and journey test
      name: Integration test against Docker 18.03.1
      before_install: ./travis/install_docker.sh docker-ce=18.03.1~ce-0~ubuntu
      script: ./gradlew integrationTest
      workspaces:
        use:
          - build_workspace

    - stage: Integration and journey test
      name: Journey test against Docker 18.03.1
      before_install: ./travis/install_docker.sh docker-ce=18.03.1~ce-0~ubuntu
      script: ./gradlew journeyTest
      workspaces:
        use:
          - build_workspace

    - stage: Integration and journey test
      name: Wait for Windows build to complete
      if: (tag IS present OR branch = "master") AND repo = "batect/batect" AND type != pull_request
      script: ./travis/wait_for_appveyor.sh

    - stage: Release
      script: skip
      if: tag IS present AND repo = "batect/batect"
      workspaces:
        use:
        - build_workspace
      before_deploy: ./gradlew --parallel validateRelease
      deploy:
        - provider: bintray
          file: build/bintray/descriptor.json
          user: charleskorn
          key:
            secure: "AIpNHq0sPOeQ+0OW9wBK15FSqZoA+zKGbRvRF0aV4W5PslkLOW4NDoMYv0JR1MCX79q7l0O7VbD3OcNkycTMjaOvsNaoZgzrB2nmtJjQLkKUDgwNGbqOSZLaQM2G2wK7yqjAiNGeNwwkz6rGBGRKqd6ZK//IvivZPBoHQnt186mndvUZ7Ltss2pkwy6q3ZJ5LqyNq+EwxIS8OtWVv8bSTXN5NiRUrVih8mzn+glZ29z/dt1KZlZQc8GwQ/CrH3UhiIVmxQNdUFm7ktOAGsMGX9czKlWHogYC1GikTskRz+SX7gCkps1y4r12lIaGxO1s4nmrs3d/MhGl03Dqqs16VIHskcuHYSEv7d7jRhnX6FS9j9OCW3OYL/CkZ6IQfNhdo/szRcs+IS7Hkixgy4J3SoEmzEnWuRS+tX2GATwnt/B4dOuo/1GIOKhvCWw3XlPg+cwnmUNZ5JLmFpcdkCAKgWHabSDi6hXh4b6wvVrmVbD+7gUP0IQNADARedE1XlDtrzD8lyHOX3UB6Uq7qO4YjSmT4aoUHNmQJZDnp9FWEgUpLR7Dekmi0JROsDGthwS3aEFEa7VLCOPUJFf42xjnX9aq2SXAhVN2bk8hYid+dmZjXWiGZZTv/xKPD4hNAffr55MVGUs9/FIdAkyRmpIxSiVcc79y1GjWxbnKfXh3Fg8="
          skip_cleanup: true
          on:
            repo: batect/batect
            all_branches: true

        - provider: releases
          api_key:
            secure: "XAYrEzKlCneQQ9iQh+U9JBBdB6lFGUA0yMwIui4i3pzHUkVZs6J3FiASRhZAwfcHtT8TB4lTRArAYQyo3gg7pDbXEJrJwnydgN2TQYQHLy58rl5QVFVBaUL1HthnqvMUQd/i+tJRHzrPJPatVRSngXmnrqoP01AEyqz9997SJesU3QUNhvvtLZvi2PWr10TwL4+QE4exY72hjT068INEJfEl0mALg7DrMdri0MSbc3EwOtaTS9EmUlyorQWBXbsZ//9ajtqHkotIMYdbMdtSB2J+O9M7LuctMHP77gJ/a8CnPnWe0ZSp2HfTLolnAJrQ8nL9NEkqbznicAJ+9cQ1p+gVObt0pu0gbZl+5OVnq4PDyiyp0st3TSbLS8U9uVjrT+9DMFq8ckfL7SggOlOTCrpRaNqIN6i9X85TwP67Yt5bRfQtRBG5NdF2efSprS+pyIBZjQkkR9/k8FP2xLpAF/5Ah4uxYnOqIB5YWFvYLnlgwtgsEi6h2HCu2+5QvezlhCsvWIJ5ATC3gIzWjHi0+GoYTW6A4zU36tWkZkG11W+0aQ0jib2d0HRHHSI7VVXJeIyQoDufxS/nJkxM0/xoOtheK7QksLdyh2M/9qwjQ9g9Km2XZnozRzMnCbl50do2KNQhwzgztDu8C0Qk75zVBCo46ceWwoPvqLrEUgS3260="
          skip_cleanup: true
          file_glob: true
          file: build/release/*
          on:
            # We skip this whole stage if we don't want to deploy, so just disable the checks here.
            condition: true
            all_branches: true

        - provider: pages
          local_dir: docs/build/docs
          skip_cleanup: true
          github_token:
            secure: "frN06reTjabvZa00wyDKeFAaeJWhEOaqiM4LH+i66H9zs2zCWvk5IsArA0zISCFtD3z2e8i031SrzOopoJULLCEU3y24vzezojP1yhTHyCEhR9sKte4Zr6eCzBEsNrt2QWW03Z1f/Z7P9Iy1IKYnW+NUxI7o/1qOpEVDqliHNltRtDbSdixDY1Q2cyKElYzpAMSezmHL8G2wn2TRtKdHrYB9nSUmoT/gy1b9feJbP6mL8cCJ9S7IdAY/rpFXrov5IbSFjoF4e8z5CmvnEb/NpbrdZHbHvcS5sqztBd2Ki6Yy/9C6srYT3Pc8hfNx0Pw4JU33XzKT23C0wxyxer/usueuGhh9Hv0O+n+YJUtsvu4beQxS9GFXuVe98tbhCrKGiGY0bYF5iT+e1OBrp94DcO4yFs5e86wH8W1U0DYqfwWCHs7mrJFQeEfl2zdEQOtGr+jXK2w48GL+X1rXeIf9v5KeruN+ht+CXyIaZ1rtYoU9ozNfVVTDDaiacIiu8fd1ejS10B5Bk1J86JlHwl/g6M9F1BkO45lKm1IMXhMx78EX1MngxVZi9vcfXZQOibbCmJ0/20CkcPYxw9EGoGBMi0HSMVbSNU6sX594HURYsF9TItA2MekxMC9K33AkSja4rHpVdph7NP1C4R9pSGnV4Nej60F8JBSQLs0V0Ihyd4s="
          target_branch: gh-pages
          keep_history: true
          on:
            # We skip this whole stage if we don't want to deploy, so just disable the checks here.
            condition: true
            all_branches: true


before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/
  - rm -fr $HOME/.gradle/caches/*/scripts/
  - rm -fr $HOME/.gradle/caches/*/scripts-remapped/
  - rm -fr $HOME/.gradle/caches/*/fileHashes/
  - rm -f  $HOME/.gradle/caches/*/fileContent/*.lock
  - rm -f  $HOME/.gradle/caches/*/javaCompile/*.lock
  - rm -f  $HOME/.gradle/caches/*/executionHistory/*.lock
  - rm -f  $HOME/.gradle/caches/*/generated-gradle-jars/*.lock
  - rm -f  $HOME/.gradle/caches/jars-3/*.lock
  - rm -f  $HOME/.gradle/caches/transforms-1/transforms-1.lock
  - rm -f  $HOME/.gradle/caches/journal-1/file-access.bin
  - rm -f  $HOME/.gradle/caches/journal-1/*.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
