language: java
sudo: required

services:
  - docker

jobs:
  include:
    - stage: lint
      install: skip
      script: ./gradlew spotlessCheck

    - stage: unit test
      install: skip
      script: ./gradlew check

    - stage: journey test
      before_install:
        - curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        - sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        - sudo apt-get update
        - sudo apt-get -y install docker-ce
        - docker --version
      script: ./gradlew journeyTest

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
