image: java:8

pipelines:
  default:
    - step:
        caches:
          - gradle
          - gradlewrapper
        script:
          - ./gradlew --no-daemon build
          # TODO: add running journey tests

definitions:
  caches:
    gradlewrapper: ~/.gradle/wrapper
