project_name: task-with-healthy-dependency-test

containers:
  build-env:
    build_directory: build-env
    dependencies:
      - http-server

  http-server:
    build_directory: http-server


tasks:
  the-task:
    run:
      container: build-env
      command: "sh -c 'echo Status code for request: $(curl --fail --silent --show-error -o /dev/null -w \"%{http_code}\" http://http-server/index.html)'"

