project_name: simple-task-dockerfile-command-test

containers:
  build-env:
    build_directory: build-env
    command: sh -c "echo 'This is some output from the task' && exit 123"

tasks:
  the-task:
    run:
      container: build-env
